# Generated by Django 5.2 on 2025-05-12 02:38

import django.db.models.deletion
import potato.models_dir.FHIR_DataTypes.FHIR_primitive
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhir_careteam',
            name='managingOrganization',
            field=models.ManyToManyField(blank=True, related_name='CareTeam_managingOrganization', to='potato.fhir_organization'),
        ),
        migrations.AddField(
            model_name='fhir_careteam',
            name='name',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_careteam',
            name='period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_period', to='potato.fhir_gp_period'),
        ),
        migrations.AddField(
            model_name='fhir_careteam',
            name='status',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_CodeField(blank=True, choices=[('proposed', 'Proposed'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('entered-in-error', 'Entered-in-error')], null=True),
        ),
        migrations.AddField(
            model_name='fhir_careteam',
            name='subject_Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_subject', to='potato.fhir_group'),
        ),
        migrations.AddField(
            model_name='fhir_careteam',
            name='subject_Patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_subject', to='potato.fhir_patient'),
        ),
        migrations.CreateModel(
            name='FHIR_CareTeam_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('CareTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CareTeam_category', to='potato.fhir_careteam')),
                ('category_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='CareTeam_category', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_CareTeam_identifier',
            fields=[
                ('fhir_gp_identifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='potato.fhir_gp_identifier')),
                ('CareTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CareTeam_identifier', to='potato.fhir_careteam')),
            ],
            bases=('potato.fhir_gp_identifier',),
        ),
        migrations.CreateModel(
            name='FHIR_CareTeam_note',
            fields=[
                ('fhir_gp_annotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='potato.fhir_gp_annotation')),
                ('CareTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CareTeam_note', to='potato.fhir_careteam')),
            ],
            bases=('potato.fhir_gp_annotation',),
        ),
        migrations.CreateModel(
            name='FHIR_CareTeam_participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('CareTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CareTeam_participant', to='potato.fhir_careteam')),
                ('effective_Period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_effective_Period', to='potato.fhir_gp_period')),
                ('effective_Timing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_effective_Timing', to='potato.fhir_gp_timing')),
                ('member_CareTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_member', to='potato.fhir_careteam')),
                ('member_Group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_member', to='potato.fhir_group')),
                ('member_Organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_member', to='potato.fhir_organization')),
                ('member_Patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_member', to='potato.fhir_patient')),
                ('member_Practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_member', to='potato.fhir_practitioner')),
                ('member_PractitionerRole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_member', to='potato.fhir_practitionerrole')),
                ('member_RelatedPerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_member', to='potato.fhir_relatedperson')),
                ('onBehalfOf_CareTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_onBehalfOf', to='potato.fhir_careteam')),
                ('onBehalfOf_Group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_onBehalfOf', to='potato.fhir_group')),
                ('onBehalfOf_Organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_onBehalfOf', to='potato.fhir_organization')),
                ('onBehalfOf_Patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_onBehalfOf', to='potato.fhir_patient')),
                ('onBehalfOf_Practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_onBehalfOf', to='potato.fhir_practitioner')),
                ('onBehalfOf_PractitionerRole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_onBehalfOf', to='potato.fhir_practitionerrole')),
                ('onBehalfOf_RelatedPerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_participant_onBehalfOf', to='potato.fhir_relatedperson')),
                ('role_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='CareTeam_participant_role', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_CareTeam_reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('CareTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CareTeam_reason', to='potato.fhir_careteam')),
                ('reason_Condition_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CareTeam_reason_Condition', to='potato.fhir_condition')),
                ('reason_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='CareTeam_reason', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_CareTeam_telecom',
            fields=[
                ('fhir_gp_contactpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='potato.fhir_gp_contactpoint')),
                ('CareTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CareTeam_telecom', to='potato.fhir_careteam')),
            ],
            bases=('potato.fhir_gp_contactpoint',),
        ),
    ]
