# Generated by Django 3.2.25 on 2025-01-12 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhir_gp_coding',
            name='binding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='potato.fhir_gp_binding'),
        ),
    ]
