# Generated by Django 3.2.25 on 2024-12-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhir_patient',
            name='general_practitioner_organization',
        ),
        migrations.RemoveField(
            model_name='fhir_patient',
            name='general_practitioner_practitioner',
        ),
        migrations.RemoveField(
            model_name='fhir_patient',
            name='general_practitioner_practitionerRole',
        ),
        migrations.RemoveField(
            model_name='fhir_patient',
            name='general_practitioner_reference',
        ),
        migrations.CreateModel(
            name='FHIR_Patient_GeneralPractitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_practitioner_organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_generalPractitioner_organization', to='potato.fhir_organization')),
                ('general_practitioner_practitioner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_generalPractitioner_practitioner', to='potato.fhir_practitioner')),
                ('general_practitioner_practitionerRole', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_generalPractitioner_practitionerRole', to='potato.fhir_practitionerrole')),
                ('general_practitioner_reference', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_generalPractitioner', to='potato.fhir_sp_reference')),
            ],
        ),
    ]
