# Generated by Django 5.2 on 2025-04-27 19:07

import django.db.models.deletion
import potato.models_dir.FHIR_DataTypes.FHIR_primitive
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fhir_allergyintolerance',
            old_name='onset',
            new_name='onset_string',
        ),
        migrations.RenameField(
            model_name='fhir_immunization',
            old_name='occurrence',
            new_name='occurrence_string',
        ),
        migrations.RenameField(
            model_name='fhir_observation',
            old_name='effective',
            new_name='effective_instant',
        ),
        migrations.RenameField(
            model_name='fhir_observation',
            old_name='value_cctext',
            new_name='value_CodeableConcept_cctext',
        ),
        migrations.RenameField(
            model_name='fhir_observation_component',
            old_name='value_cctext',
            new_name='value_CodeableConcept_cctext',
        ),
        migrations.RenameField(
            model_name='fhir_patient',
            old_name='multipleBirth',
            new_name='deceased_boolean',
        ),
        migrations.RenameField(
            model_name='fhir_patient',
            old_name='deceased',
            new_name='deceased_dateTime',
        ),
        migrations.RenameField(
            model_name='fhir_practitioner',
            old_name='deceased',
            new_name='deceased_dateTime',
        ),
        migrations.RemoveField(
            model_name='fhir_observation',
            name='instantiates',
        ),
        migrations.RemoveField(
            model_name='fhir_observation',
            name='value',
        ),
        migrations.RemoveField(
            model_name='fhir_observation',
            name='value_cc',
        ),
        migrations.RemoveField(
            model_name='fhir_observation_component',
            name='value',
        ),
        migrations.RemoveField(
            model_name='fhir_observation_component',
            name='value_cc',
        ),
        migrations.AddField(
            model_name='fhir_allergyintolerance',
            name='onset_Age',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AllergyIntolerance_onset_Age', to='potato.fhir_gp_quantity_age'),
        ),
        migrations.AddField(
            model_name='fhir_allergyintolerance',
            name='onset_Period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AllergyIntolerance_onset_Period', to='potato.fhir_gp_period'),
        ),
        migrations.AddField(
            model_name='fhir_allergyintolerance',
            name='onset_Range',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AllergyIntolerance_onset_Range', to='potato.fhir_gp_range'),
        ),
        migrations.AddField(
            model_name='fhir_allergyintolerance',
            name='onset_dateTime',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_immunization',
            name='occurrence_dateTime',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='effective_Period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_effective_Period', to='potato.fhir_gp_period'),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='effective_Timing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_effective_Timing', to='potato.fhir_gp_timing'),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='effective_dateTime',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='instantiates_Reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_instantiates_Reference', to='potato.fhir_observationdefinition'),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='instantiates_canonical',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_CanonicalField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='value_Attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_value_Attachment', to='potato.fhir_gp_attachment'),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='value_CodeableConcept_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='Observation_value_CodeableConcept', to='potato.fhir_gp_coding'),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='value_Period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_value_Period', to='potato.fhir_gp_period'),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='value_Quantity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_value_Quantity', to='potato.fhir_gp_quantity'),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='value_Range',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_value_Range', to='potato.fhir_gp_range'),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='value_Ratio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_value_Ratio', to='potato.fhir_gp_ratio'),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='value_Reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_value_Reference', to='potato.fhir_molecularsequence'),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='value_SampledData',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_value_SampledData', to='potato.fhir_gp_sampleddata'),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='value_boolean',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='value_dateTime',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='value_string',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_observation',
            name='value_time',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_observation_component',
            name='value_Attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_component_value_Attachment', to='potato.fhir_gp_attachment'),
        ),
        migrations.AddField(
            model_name='fhir_observation_component',
            name='value_CodeableConcept_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='Observation_component_value_CodeableConcept', to='potato.fhir_gp_coding'),
        ),
        migrations.AddField(
            model_name='fhir_observation_component',
            name='value_Period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_component_value_Period', to='potato.fhir_gp_period'),
        ),
        migrations.AddField(
            model_name='fhir_observation_component',
            name='value_Quantity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_component_value_Quantity', to='potato.fhir_gp_quantity'),
        ),
        migrations.AddField(
            model_name='fhir_observation_component',
            name='value_Range',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_component_value_Range', to='potato.fhir_gp_range'),
        ),
        migrations.AddField(
            model_name='fhir_observation_component',
            name='value_Ratio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_component_value_Ratio', to='potato.fhir_gp_ratio'),
        ),
        migrations.AddField(
            model_name='fhir_observation_component',
            name='value_Reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_component_value_Reference', to='potato.fhir_molecularsequence'),
        ),
        migrations.AddField(
            model_name='fhir_observation_component',
            name='value_SampledData',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Observation_component_value_SampledData', to='potato.fhir_gp_sampleddata'),
        ),
        migrations.AddField(
            model_name='fhir_observation_component',
            name='value_boolean',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_observation_component',
            name='value_dateTime',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_observation_component',
            name='value_string',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_observation_component',
            name='value_time',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_patient',
            name='multipleBirth_boolean',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_practitioner',
            name='deceased_boolean',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_allergyintolerance',
            name='clinicalStatus_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'https://www.hl7.org/fhir/valueset-allergyintolerance-clinical.html'}, related_name='AllergyIntolerance_clinicalStatus', to='potato.fhir_gp_coding'),
        ),
        migrations.AlterField(
            model_name='fhir_allergyintolerance',
            name='code_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'https://www.hl7.org/fhir/valueset-allergyintolerance-code.html'}, related_name='AllergyIntolerance_code', to='potato.fhir_gp_coding'),
        ),
        migrations.AlterField(
            model_name='fhir_allergyintolerance',
            name='type_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'https://www.hl7.org/fhir/valueset-allergy-intolerance-type.html'}, related_name='AllergyIntolerance_type', to='potato.fhir_gp_coding'),
        ),
        migrations.AlterField(
            model_name='fhir_allergyintolerance',
            name='verificationStatus_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'https://www.hl7.org/fhir/valueset-allergyintolerance-verification.html'}, related_name='AllergyIntolerance_verificationStatus', to='potato.fhir_gp_coding'),
        ),
        migrations.AlterField(
            model_name='fhir_allergyintolerance_reaction',
            name='exposureRoute_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'https://www.hl7.org/fhir/valueset-route-codes.html'}, related_name='AllergyIntolerance_reaction_exposureRoute', to='potato.fhir_gp_coding'),
        ),
        migrations.AlterField(
            model_name='fhir_allergyintolerance_reaction',
            name='substance_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'https://www.hl7.org/fhir/valueset-substance-code.html'}, related_name='AllergyIntolerance_reaction_substance', to='potato.fhir_gp_coding'),
        ),
        migrations.AlterField(
            model_name='fhir_allergyintolerance_reaction_manifestation',
            name='manifestation_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'https://www.hl7.org/fhir/valueset-clinical-findings.html'}, related_name='AllergyIntolerance_reaction_manifestation', to='potato.fhir_gp_coding'),
        ),
    ]
