# Generated by Django 5.2 on 2025-04-30 03:49

import potato.models_dir.FHIR_DataTypes.FHIR_primitive
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhir_gp_money',
            name='value',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_gp_quantity',
            name='value',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fhir_gp_sampleddata',
            name='factor',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_gp_sampleddata',
            name='interval',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_gp_sampleddata',
            name='lowerLimit',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_gp_sampleddata',
            name='upperLimit',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_gp_timing',
            name='repeat_duration',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_gp_timing',
            name='repeat_durationMax',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_gp_timing',
            name='repeat_period',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_gp_timing',
            name='repeat_periodMax',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_location_position',
            name='altitude',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_location_position',
            name='latitude',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_location_position',
            name='longitude',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
