# Generated by Django 5.2 on 2025-04-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fhir_allergyintolerance',
            old_name='encounter_Encounter',
            new_name='encounter',
        ),
        migrations.RenameField(
            model_name='fhir_allergyintolerance',
            old_name='patient_Patient',
            new_name='patient',
        ),
    ]
