# Generated by Django 5.2 on 2025-05-17 17:38

import django.db.models.deletion
import potato.models_dir.FHIR_DataTypes.FHIR_primitive
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0002_fhir_careteam_managingorganization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhir_list',
            name='code_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='List_code', to='potato.fhir_gp_coding'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='code_cctext',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='date',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='emptyReason_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='List_emptyReason', to='potato.fhir_gp_coding'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='emptyReason_cctext',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='List_encounter', to='potato.fhir_encounter'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='mode',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_CodeField(blank=True, choices=[('working', 'Working'), ('snapshot', 'Snapshot'), ('changes', 'Changes')], null=True),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='orderedBy_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='List_orderedBy', to='potato.fhir_gp_coding'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='orderedBy_cctext',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='source_CareTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='List_source', to='potato.fhir_careteam'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='source_Device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='List_source', to='potato.fhir_device'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='source_Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='List_source', to='potato.fhir_group'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='source_Organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='List_source', to='potato.fhir_organization'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='source_Patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='List_source', to='potato.fhir_patient'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='source_Practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='List_source', to='potato.fhir_practitioner'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='source_PractitionerRole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='List_source', to='potato.fhir_practitionerrole'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='source_RelatedPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='List_source', to='potato.fhir_relatedperson'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='status',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_CodeField(blank=True, choices=[('current', 'Current'), ('retired', 'Retired'), ('entered-in-error', 'Entered-in-error')], null=True),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='title',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FHIR_List_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('deleted', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_BooleanField(blank=True, null=True)),
                ('date', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(blank=True, null=True)),
                ('List', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='List_entry', to='potato.fhir_list')),
                ('flag_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='List_entry_flag', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_List_identifier',
            fields=[
                ('fhir_gp_identifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='potato.fhir_gp_identifier')),
                ('List', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='List_identifier', to='potato.fhir_list')),
            ],
            bases=('potato.fhir_gp_identifier',),
        ),
        migrations.CreateModel(
            name='FHIR_List_note',
            fields=[
                ('fhir_gp_annotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='potato.fhir_gp_annotation')),
                ('List', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='List_note', to='potato.fhir_list')),
            ],
            bases=('potato.fhir_gp_annotation',),
        ),
    ]
