# Generated by Django 3.2.25 on 2024-12-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0002_auto_20241226_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhir_gp_humanname',
            name='use',
            field=models.CharField(blank=True, choices=[('usual', 'Usual'), ('official', 'Official'), ('temp', 'Temporary'), ('nickname', 'Nickname'), ('anonymous', 'Anonymous'), ('old', 'Old'), ('maiden', 'Maiden')], max_length=20, null=True),
        ),
    ]
