# Generated by Django 3.2.25 on 2025-01-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0002_fhir_gp_coding_binding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhir_gp_coding',
            name='binding',
        ),
        migrations.AddField(
            model_name='fhir_gp_coding',
            name='binding',
            field=models.ManyToManyField(blank=True, null=True, related_name='bindings', to='potato.FHIR_GP_Binding'),
        ),
    ]
