# Generated by Django 3.2.25 on 2025-01-04 01:17

from django.db import migrations
import potato.FHIR_DataTypes.FHIR_primitive


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0002_auto_20250103_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhir_patient',
            name='deceased_date_time',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(null=True),
        ),
    ]
