# Generated by Django 5.2 on 2025-05-17 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0003_fhir_list_code_cc_fhir_list_code_cctext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhir_list_entry',
            name='item_Device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='List_entry_item', to='potato.fhir_device'),
        ),
        migrations.AddField(
            model_name='fhir_list_entry',
            name='item_Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='List_entry_item', to='potato.fhir_group'),
        ),
        migrations.AddField(
            model_name='fhir_list_entry',
            name='item_Patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='List_entry_item', to='potato.fhir_patient'),
        ),
        migrations.AddField(
            model_name='fhir_list_entry',
            name='item_Practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='List_entry_item', to='potato.fhir_practitioner'),
        ),
    ]
