# Generated by Django 3.2.25 on 2025-01-04 02:26

from django.db import migrations
import potato.FHIR_DataTypes.FHIR_primitive


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0003_alter_fhir_patient_deceased_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhir_patient',
            name='birthDate_datetime',
        ),
        migrations.RemoveField(
            model_name='fhir_patient',
            name='birthDate_datetime_precision',
        ),
        migrations.AddField(
            model_name='fhir_patient',
            name='birthDate_date',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_patient',
            name='birthDate_date_precision',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateField_Precision(blank=True, choices=[('year', 'Year'), ('month', 'Month'), ('day', 'Day')], default='day', max_length=5, null=True),
        ),
    ]
