# Generated by Django 5.2 on 2025-05-18 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0004_fhir_list_entry_item_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhir_list',
            name='subject_Device',
            field=models.ManyToManyField(blank=True, related_name='List_subject', to='potato.fhir_device'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='subject_Group',
            field=models.ManyToManyField(blank=True, related_name='List_subject', to='potato.fhir_group'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='subject_Patient',
            field=models.ManyToManyField(blank=True, related_name='List_subject', to='potato.fhir_patient'),
        ),
        migrations.AddField(
            model_name='fhir_list',
            name='subject_Practitioner',
            field=models.ManyToManyField(blank=True, related_name='List_subject', to='potato.fhir_practitioner'),
        ),
        migrations.AlterField(
            model_name='fhir_list_entry',
            name='item_Device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='List_entry_item', to='potato.fhir_device'),
        ),
        migrations.AlterField(
            model_name='fhir_list_entry',
            name='item_Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='List_entry_item', to='potato.fhir_group'),
        ),
        migrations.AlterField(
            model_name='fhir_list_entry',
            name='item_Patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='List_entry_item', to='potato.fhir_patient'),
        ),
        migrations.AlterField(
            model_name='fhir_list_entry',
            name='item_Practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='List_entry_item', to='potato.fhir_practitioner'),
        ),
    ]
