# Generated by Django 3.2.25 on 2025-01-12 16:57

from django.db import migrations, models
import django.db.models.deletion
import potato.FHIR_DataTypes.FHIR_primitive


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0004_auto_20250112_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fhir_allergyintolerance',
            old_name='category',
            new_name='category_cc',
        ),
        migrations.RenameField(
            model_name='fhir_allergyintolerance',
            old_name='clinical_status',
            new_name='clinical_status_cc',
        ),
        migrations.RenameField(
            model_name='fhir_allergyintolerance',
            old_name='criticality',
            new_name='criticality_cc',
        ),
        migrations.RenameField(
            model_name='fhir_allergyintolerance',
            old_name='type',
            new_name='type_cc',
        ),
        migrations.RenameField(
            model_name='fhir_allergyintolerance',
            old_name='verification_status',
            new_name='verification_status_cc',
        ),
        migrations.RenameField(
            model_name='fhir_patient',
            old_name='marital_status',
            new_name='marital_status_cc',
        ),
        migrations.RenameField(
            model_name='fhir_patient',
            old_name='marital_status_text',
            new_name='marital_status_cctext',
        ),
        migrations.AddField(
            model_name='fhir_gp_identifier',
            name='type_cctext',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fhir_patient_communication',
            name='language_cc',
            field=models.ManyToManyField(limit_choices_to={'binding__binding_rule': 'https://www.hl7.org/fhir/valueset-languages.html'}, related_name='patient_communication_language', to='potato.FHIR_GP_Coding'),
        ),
        migrations.AddField(
            model_name='fhir_patient_communication',
            name='language_cctext',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='FHIR_Patient_Contact_Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_contact_relationships', to='potato.fhir_patient_contact')),
                ('relationship_cc', models.ManyToManyField(limit_choices_to={'binding__binding_rule': 'https://www.hl7.org/fhir/valueset-patient-contactrelationship.html'}, related_name='patient_contact_relationship_cc', to='potato.FHIR_GP_Coding')),
            ],
        ),
    ]
