# Generated by Django 3.2.25 on 2025-01-12 17:19

from django.db import migrations
import potato.FHIR_DataTypes.FHIR_primitive


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0006_auto_20250112_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhir_allergyintolerance_participant',
            name='function_cctext',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True),
        ),
    ]
