# Generated by Django 5.2 on 2025-05-27 00:28

import django.db.models.deletion
import potato.models_dir.FHIR_DataTypes.FHIR_primitive
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0006_fhir_diagnosticreport_basedon_careplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='basedOn',
            field=models.ManyToManyField(blank=True, related_name='MedicationAdministration_basedOn', to='potato.fhir_careplan'),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_encounter', to='potato.fhir_encounter'),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='eventHistory',
            field=models.ManyToManyField(blank=True, related_name='MedicationAdministration_eventHistory', to='potato.fhir_provenance'),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='isSubPotent',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='medication_Medication_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_medication_Medication', to='potato.fhir_medication'),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='medication_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationAdministration_medication', to='potato.fhir_gp_coding'),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='medication_cctext',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='occurrence_Period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_occurrence_Period', to='potato.fhir_gp_period'),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='occurrence_Timing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_occurrence_Timing', to='potato.fhir_gp_timing'),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='occurrence_dateTime',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='partOf_MedicationAdministration',
            field=models.ManyToManyField(blank=True, related_name='MedicationAdministration_partOf', to='potato.fhir_medicationadministration'),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='partOf_MedicationDispense',
            field=models.ManyToManyField(blank=True, related_name='MedicationAdministration_partOf', to='potato.fhir_medicationdispense'),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='partOf_Procedure',
            field=models.ManyToManyField(blank=True, related_name='MedicationAdministration_partOf', to='potato.fhir_procedure'),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='recorded',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_request', to='potato.fhir_medicationrequest'),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='status',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_CodeField(blank=True, choices=[('in-progress', 'In-progress'), ('not-done', 'Not-done'), ('on-hold', 'On-hold'), ('completed', 'Completed'), ('entered-in-error', 'Entered-in-error'), ('stopped', 'Stopped'), ('unknown', 'Unknown')], null=True),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='subject_Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_subject', to='potato.fhir_group'),
        ),
        migrations.AddField(
            model_name='fhir_medicationadministration',
            name='subject_Patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_subject', to='potato.fhir_patient'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='authorizingPrescription',
            field=models.ManyToManyField(blank=True, related_name='MedicationDispense_authorizingPrescription', to='potato.fhir_medicationrequest'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='basedOn',
            field=models.ManyToManyField(blank=True, related_name='MedicationDispense_basedOn', to='potato.fhir_careplan'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='daysSupply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_daysSupply', to='potato.fhir_gp_quantity'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_destination', to='potato.fhir_location'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_encounter', to='potato.fhir_encounter'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='eventHistory',
            field=models.ManyToManyField(blank=True, related_name='MedicationDispense_eventHistory', to='potato.fhir_provenance'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='fillNumber',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_PositiveIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_location', to='potato.fhir_location'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='medication_Medication_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_medication_Medication', to='potato.fhir_medication'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='medication_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationDispense_medication', to='potato.fhir_gp_coding'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='medication_cctext',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='notPerformedReason_DetectedIssue_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_notPerformedReason_DetectedIssue', to='potato.fhir_detectedissue'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='notPerformedReason_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationDispense_notPerformedReason', to='potato.fhir_gp_coding'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='notPerformedReason_cctext',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='partOf_MedicationAdministration',
            field=models.ManyToManyField(blank=True, related_name='MedicationDispense_partOf', to='potato.fhir_medicationadministration'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='partOf_Procedure',
            field=models.ManyToManyField(blank=True, related_name='MedicationDispense_partOf', to='potato.fhir_procedure'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='quantity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_quantity', to='potato.fhir_gp_quantity'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='receiver_Group',
            field=models.ManyToManyField(blank=True, related_name='MedicationDispense_receiver', to='potato.fhir_group'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='receiver_Location',
            field=models.ManyToManyField(blank=True, related_name='MedicationDispense_receiver', to='potato.fhir_location'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='receiver_Patient',
            field=models.ManyToManyField(blank=True, related_name='MedicationDispense_receiver', to='potato.fhir_patient'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='receiver_Practitioner',
            field=models.ManyToManyField(blank=True, related_name='MedicationDispense_receiver', to='potato.fhir_practitioner'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='receiver_PractitionerRole',
            field=models.ManyToManyField(blank=True, related_name='MedicationDispense_receiver', to='potato.fhir_practitionerrole'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='receiver_RelatedPerson',
            field=models.ManyToManyField(blank=True, related_name='MedicationDispense_receiver', to='potato.fhir_relatedperson'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='recorded',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='renderedDosageInstruction',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_MarkdownField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='status',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_CodeField(blank=True, choices=[('preparation', 'Preparation'), ('in-progress', 'In-progress'), ('cancelled', 'Cancelled'), ('on-hold', 'On-hold'), ('completed', 'Completed'), ('entered-in-error', 'Entered-in-error'), ('stopped', 'Stopped'), ('declined', 'Declined'), ('unknown', 'Unknown')], null=True),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='statusChanged',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='subject_Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_subject', to='potato.fhir_group'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='subject_Patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_subject', to='potato.fhir_patient'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='type_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationDispense_type', to='potato.fhir_gp_coding'),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='type_cctext',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='whenHandedOver',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_medicationdispense',
            name='whenPrepared',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_medicationrequest',
            name='medication_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'https://build.fhir.org/valueset-medication-codes.html'}, related_name='MedicationRequest_medication', to='potato.fhir_gp_coding'),
        ),
        migrations.CreateModel(
            name='FHIR_MedicationAdministration_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('MedicationAdministration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationAdministration_category', to='potato.fhir_medicationadministration')),
                ('category_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationAdministration_category', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_MedicationAdministration_device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('MedicationAdministration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationAdministration_device', to='potato.fhir_medicationadministration')),
                ('device_Device_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_device_Device', to='potato.fhir_device')),
                ('device_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationAdministration_device', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_MedicationAdministration_dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, null=True)),
                ('site_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('route_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('method_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('MedicationAdministration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationAdministration_dosage', to='potato.fhir_medicationadministration')),
                ('dose', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_dosage_dose', to='potato.fhir_gp_quantity')),
                ('method_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationAdministration_dosage_method', to='potato.fhir_gp_coding')),
                ('rate_Quantity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_dosage_rate_Quantity', to='potato.fhir_gp_quantity')),
                ('rate_Ratio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_dosage_rate_Ratio', to='potato.fhir_gp_ratio')),
                ('route_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationAdministration_dosage_route', to='potato.fhir_gp_coding')),
                ('site_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationAdministration_dosage_site', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_MedicationAdministration_identifier',
            fields=[
                ('fhir_gp_identifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='potato.fhir_gp_identifier')),
                ('MedicationAdministration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationAdministration_identifier', to='potato.fhir_medicationadministration')),
            ],
            bases=('potato.fhir_gp_identifier',),
        ),
        migrations.CreateModel(
            name='FHIR_MedicationAdministration_note',
            fields=[
                ('fhir_gp_annotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='potato.fhir_gp_annotation')),
                ('MedicationAdministration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationAdministration_note', to='potato.fhir_medicationadministration')),
            ],
            bases=('potato.fhir_gp_annotation',),
        ),
        migrations.CreateModel(
            name='FHIR_MedicationAdministration_performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('actor_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('MedicationAdministration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationAdministration_performer', to='potato.fhir_medicationadministration')),
                ('actor_Device_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_performer_actor_Device', to='potato.fhir_device')),
                ('actor_Group_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_performer_actor_Group', to='potato.fhir_group')),
                ('actor_Patient_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_performer_actor_Patient', to='potato.fhir_patient')),
                ('actor_PractitionerRole_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_performer_actor_PractitionerRole', to='potato.fhir_practitionerrole')),
                ('actor_Practitioner_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_performer_actor_Practitioner', to='potato.fhir_practitioner')),
                ('actor_RelatedPerson_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_performer_actor_RelatedPerson', to='potato.fhir_relatedperson')),
                ('actor_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationAdministration_performer_actor', to='potato.fhir_gp_coding')),
                ('function_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationAdministration_performer_function', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_MedicationAdministration_reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('MedicationAdministration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationAdministration_reason', to='potato.fhir_medicationadministration')),
                ('reason_Condition_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_reason_Condition', to='potato.fhir_condition')),
                ('reason_DiagnosticReport_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_reason_DiagnosticReport', to='potato.fhir_diagnosticreport')),
                ('reason_Observation_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_reason_Observation', to='potato.fhir_observation')),
                ('reason_Procedure_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationAdministration_reason_Procedure', to='potato.fhir_procedure')),
                ('reason_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationAdministration_reason', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_MedicationAdministration_statusReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusReason_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('MedicationAdministration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationAdministration_statusReason', to='potato.fhir_medicationadministration')),
                ('statusReason_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationAdministration_statusReason', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_MedicationAdministration_subPotentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subPotentReason_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('MedicationAdministration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationAdministration_subPotentReason', to='potato.fhir_medicationadministration')),
                ('subPotentReason_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationAdministration_subPotentReason', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_MedicationDispense_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('MedicationDispense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationDispense_category', to='potato.fhir_medicationdispense')),
                ('category_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationDispense_category', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_MedicationDispense_dosageInstruction',
            fields=[
                ('fhir_sp_dosage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='potato.fhir_sp_dosage')),
                ('MedicationDispense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationDispense_dosageInstruction', to='potato.fhir_medicationdispense')),
            ],
            bases=('potato.fhir_sp_dosage',),
        ),
        migrations.CreateModel(
            name='FHIR_MedicationDispense_identifier',
            fields=[
                ('fhir_gp_identifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='potato.fhir_gp_identifier')),
                ('MedicationDispense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationDispense_identifier', to='potato.fhir_medicationdispense')),
            ],
            bases=('potato.fhir_gp_identifier',),
        ),
        migrations.CreateModel(
            name='FHIR_MedicationDispense_note',
            fields=[
                ('fhir_gp_annotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='potato.fhir_gp_annotation')),
                ('MedicationDispense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationDispense_note', to='potato.fhir_medicationdispense')),
            ],
            bases=('potato.fhir_gp_annotation',),
        ),
        migrations.CreateModel(
            name='FHIR_MedicationDispense_performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('MedicationDispense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationDispense_performer', to='potato.fhir_medicationdispense')),
                ('actor_CareTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_performer_actor', to='potato.fhir_careteam')),
                ('actor_Device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_performer_actor', to='potato.fhir_device')),
                ('actor_Group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_performer_actor', to='potato.fhir_group')),
                ('actor_Organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_performer_actor', to='potato.fhir_organization')),
                ('actor_Patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_performer_actor', to='potato.fhir_patient')),
                ('actor_Practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_performer_actor', to='potato.fhir_practitioner')),
                ('actor_PractitionerRole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_performer_actor', to='potato.fhir_practitionerrole')),
                ('actor_RelatedPerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_performer_actor', to='potato.fhir_relatedperson')),
                ('function_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationDispense_performer_function', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_MedicationDispense_substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wasSubstituted', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_BooleanField(blank=True, null=True)),
                ('type_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('MedicationDispense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationDispense_substitution', to='potato.fhir_medicationdispense')),
                ('responsibleParty_Organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_substitution_responsibleParty', to='potato.fhir_organization')),
                ('responsibleParty_Practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_substitution_responsibleParty', to='potato.fhir_practitioner')),
                ('responsibleParty_PractitionerRole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MedicationDispense_substitution_responsibleParty', to='potato.fhir_practitionerrole')),
                ('type_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationDispense_substitution_type', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_MedicationDispense_substitution_reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('MedicationDispense_substitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicationDispense_substitution_reason', to='potato.fhir_medicationdispense_substitution')),
                ('reason_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='MedicationDispense_substitution_reason', to='potato.fhir_gp_coding')),
            ],
        ),
    ]
