# Generated by Django 3.2.25 on 2025-01-12 17:31

from django.db import migrations, models
import potato.FHIR_DataTypes.FHIR_primitive


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0007_fhir_allergyintolerance_participant_function_cctext'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhir_allergyintolerance_reaction',
            name='exposureRoute_cc',
            field=models.ManyToManyField(limit_choices_to={'binding__binding_rule': 'https://www.hl7.org/fhir/valueset-route-codes.html'}, related_name='allergyintolerance_reaction_exposureroute', to='potato.FHIR_GP_Coding'),
        ),
        migrations.AddField(
            model_name='fhir_allergyintolerance_reaction',
            name='exposureRoute_cctext',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='fhir_allergyintolerance_reaction',
            name='substance_cc',
            field=models.ManyToManyField(limit_choices_to={'binding__binding_rule': 'https://www.hl7.org/fhir/valueset-substance-code.html'}, related_name='allergyintolerance_reaction_substance', to='potato.FHIR_GP_Coding'),
        ),
        migrations.AddField(
            model_name='fhir_allergyintolerance_reaction',
            name='substance_cctext',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True),
        ),
    ]
