# Generated by Django 5.2 on 2025-05-28 02:41

import django.db.models.deletion
import potato.models_dir.FHIR_DataTypes.FHIR_primitive
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0007_fhir_medicationadministration_basedon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhir_sp_dosage',
            name='asNeeded',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_sp_dosage',
            name='maxDosePerAdministration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dosage_maxDosePerAdministration', to='potato.fhir_gp_quantity'),
        ),
        migrations.AddField(
            model_name='fhir_sp_dosage',
            name='maxDosePerLifetime',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dosage_maxDosePerLifetime', to='potato.fhir_gp_quantity'),
        ),
        migrations.AddField(
            model_name='fhir_sp_dosage',
            name='method_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='Dosage_method', to='potato.fhir_gp_coding'),
        ),
        migrations.AddField(
            model_name='fhir_sp_dosage',
            name='method_cctext',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='fhir_sp_dosage',
            name='patientInstruction',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_sp_dosage',
            name='route_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='Dosage_route', to='potato.fhir_gp_coding'),
        ),
        migrations.AddField(
            model_name='fhir_sp_dosage',
            name='route_cctext',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='fhir_sp_dosage',
            name='sequence',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_SignedIntField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_sp_dosage',
            name='site_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='Dosage_site', to='potato.fhir_gp_coding'),
        ),
        migrations.AddField(
            model_name='fhir_sp_dosage',
            name='site_cctext',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='fhir_sp_dosage',
            name='text',
            field=potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fhir_sp_dosage',
            name='timing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dosage_timing', to='potato.fhir_gp_timing'),
        ),
        migrations.CreateModel(
            name='FHIR_SP_Dosage_additionalInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additionalInstruction_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('Dosage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dosage_additionalInstruction', to='potato.fhir_sp_dosage')),
                ('additionalInstruction_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='Dosage_additionalInstruction', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_SP_Dosage_asNeededFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asNeededFor_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('Dosage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dosage_asNeededFor', to='potato.fhir_sp_dosage')),
                ('asNeededFor_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='Dosage_asNeededFor', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_SP_Dosage_doseAndRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cctext', potato.models_dir.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('dose_Quantity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dosage_doseAndRate_dose_Quantity', to='potato.fhir_gp_quantity')),
                ('dose_Range', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dosage_doseAndRate_dose_Range', to='potato.fhir_gp_range')),
                ('rate_Quantity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dosage_doseAndRate_rate_Quantity', to='potato.fhir_gp_quantity')),
                ('rate_Range', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dosage_doseAndRate_rate_Range', to='potato.fhir_gp_range')),
                ('rate_Ratio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dosage_doseAndRate_rate_Ratio', to='potato.fhir_gp_ratio')),
                ('type_cc', models.ManyToManyField(blank=True, limit_choices_to={'codings__binding_rule': 'TODO'}, related_name='Dosage_doseAndRate_type', to='potato.fhir_gp_coding')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_SP_Dosage_maxDosePerPeriod',
            fields=[
                ('fhir_gp_ratio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='potato.fhir_gp_ratio')),
                ('Dosage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dosage_maxDosePerPeriod', to='potato.fhir_sp_dosage')),
            ],
            bases=('potato.fhir_gp_ratio',),
        ),
    ]
