# Generated by Django 3.2.25 on 2025-01-12 19:09

from django.db import migrations, models
import django.db.models.deletion
import potato.FHIR_DataTypes.FHIR_primitive


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0009_auto_20250112_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhir_allergyintolerance_reaction',
            name='manifestation',
        ),
        migrations.AlterField(
            model_name='fhir_allergyintolerance_reaction',
            name='substance_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'binding__binding_rule': 'https://www.hl7.org/fhir/valueset-substance-code.html'}, related_name='allergyintolerance_reaction_substance', to='potato.FHIR_GP_Coding'),
        ),
        migrations.CreateModel(
            name='FHIR_AllergyIntolerance_Reaction_Manifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifestation_cctext', potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True)),
                ('manifestation_cc', models.ManyToManyField(blank=True, limit_choices_to={'binding__binding_rule': 'https://www.hl7.org/fhir/valueset-clinical-findings.html'}, related_name='allergyintolerance_reaction_manifestation_cc', to='potato.FHIR_GP_Coding')),
                ('manifestation_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potato.fhir_observation')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potato.fhir_allergyintolerance_reaction')),
            ],
        ),
    ]
