# Generated by Django 3.2.25 on 2025-01-12 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0010_auto_20250112_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhir_gp_annotation',
            name='author_type',
        ),
        migrations.AlterField(
            model_name='fhir_allergyintolerance_reaction_manifestation',
            name='manifestation_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='potato.fhir_observation'),
        ),
    ]
