# Generated by Django 3.2.25 on 2025-01-14 02:27

from django.db import migrations
import potato.FHIR_DataTypes.FHIR_primitive


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0013_fhir_observation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhir_allergyintolerance',
            name='code_cctext',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=5000, null=True),
        ),
    ]
