# Generated by Django 3.2.25 on 2025-01-17 01:06

from django.db import migrations, models
import django.db.models.deletion
import potato.FHIR_DataTypes.FHIR_primitive


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0014_fhir_allergyintolerance_code_cctext'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHIR_BiologicallyDerivedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_GP_Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_NutritionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='category',
            field=models.ManyToManyField(blank=True, limit_choices_to={'binding__binding_rule': 'https://www.hl7.org/fhir/valueset-observation-category.html'}, related_name='observation_category', to='potato.FHIR_GP_Coding'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='code',
            field=models.ManyToManyField(blank=True, limit_choices_to={'binding__binding_rule': 'https://www.hl7.org/fhir/valueset-observation-codes.html'}, related_name='observation_code', to='potato.FHIR_GP_Coding'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='effective_dateTime',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='effective_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_effective_period', to='potato.fhir_gp_period'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='effective_string',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_StringField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_encounter', to='potato.fhir_encounter'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='status',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_CodeField(choices=[('registered', 'Registered'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('amended', 'Amended'), ('corrected', 'Corrected'), ('cancelled', 'Cancelled'), ('entered-in-error', 'Entered in Error'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='subject_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_subject_device', to='potato.fhir_device'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='subject_medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_subject_medication', to='potato.fhir_medication'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='subject_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_subject_organization', to='potato.fhir_organization'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='subject_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_subject_patient', to='potato.fhir_patient'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='subject_practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_subject_practitioner', to='potato.fhir_practitioner'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='subject_practitionerRole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_subject_practitionerRole', to='potato.fhir_practitionerrole'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='subject_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_subject_procedure', to='potato.fhir_procedure'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='subject_relatedPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_subject_relatedPerson', to='potato.fhir_relatedperson'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='effective_timing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_effective_timing', to='potato.fhir_gp_timing'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='subject_biologicallyDerivedProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_subject_biologicallyDerivedProduct', to='potato.fhir_biologicallyderivedproduct'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='subject_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_subject_group', to='potato.fhir_group'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='subject_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_subject_location', to='potato.fhir_location'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='subject_nutritionProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_subject_nutritionProduct', to='potato.fhir_nutritionproduct'),
        ),
        migrations.AddField(
            model_name='triggeredbythrough',
            name='subject_substance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_subject_substance', to='potato.fhir_substance'),
        ),
    ]
