# Generated by Django 3.2.25 on 2025-01-17 01:45

from django.db import migrations, models
import django.db.models.deletion
import potato.FHIR_DataTypes.FHIR_primitive


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0016_auto_20250116_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fhir_gp_timing',
            old_name='repeat_count_max',
            new_name='repeat_countMax',
        ),
        migrations.RenameField(
            model_name='fhir_gp_timing',
            old_name='repeat_duration_max',
            new_name='repeat_durationMax',
        ),
        migrations.RenameField(
            model_name='fhir_gp_timing',
            old_name='repeat_frequency_max',
            new_name='repeat_frequencyMmax',
        ),
        migrations.RenameField(
            model_name='fhir_gp_timing',
            old_name='repeat_period_max',
            new_name='repeat_periodMax',
        ),
        migrations.RemoveField(
            model_name='fhir_gp_timing',
            name='repeat_day_of_week',
        ),
        migrations.RemoveField(
            model_name='fhir_gp_timing',
            name='repeat_period_unit',
        ),
        migrations.RemoveField(
            model_name='fhir_gp_timing',
            name='repeat_time_of_day',
        ),
        migrations.RemoveField(
            model_name='fhir_gp_timing',
            name='repeat_when',
        ),
        migrations.AddField(
            model_name='fhir_gp_timing',
            name='repeat_periodUnit',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_CodeField(blank=True, choices=[('s', 'Second'), ('min', 'Minute'), ('h', 'Hour'), ('d', 'Day'), ('wk', 'Week'), ('mo', 'Month')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_gp_timing',
            name='repeat_duration_unit',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_CodeField(blank=True, choices=[('s', 'Second'), ('min', 'Minute'), ('h', 'Hour'), ('d', 'Day'), ('wk', 'Week'), ('mo', 'Month')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='FHIR_GP_Timing_repeat_when',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_CodeField(blank=True, choices=[('MORN', 'Morning'), ('MORN.early', 'Early Morning'), ('MORN.late', 'Late Morning'), ('NOON', 'Noon'), ('AFT', 'Afternoon'), ('AFT.early', 'Early Afternoon'), ('AFT.late', 'Late Afternoon'), ('EVE', 'Evening'), ('EVE.early', 'Early Evening'), ('EVE.late', 'Late Evening'), ('NIGHT', 'Night'), ('PHS', 'After Sleep'), ('IMD', 'Immediate'), ('HS', 'Prior to Sleep'), ('WAKE', 'Upon Waking'), ('C', 'Meal'), ('CM', 'Breakfast'), ('CD', 'Lunch'), ('CV', 'Dinner'), ('AC', 'Before Meal'), ('ACM', 'Before Breakfast'), ('ACD', 'Before Lunch'), ('ACV', 'Before Dinner'), ('PC', 'After Meal'), ('PCM', 'After Breakfast'), ('PCD', 'After Lunch'), ('PCV', 'After Dinner')], max_length=20, null=True)),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_when', to='potato.fhir_gp_timing')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_GP_Timing_repeat_timeOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfDay', potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_TimeField(blank=True, null=True)),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_timeOfDay', to='potato.fhir_gp_timing')),
            ],
        ),
        migrations.CreateModel(
            name='FHIR_GP_Timing_repeat_dayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_CodeField(blank=True, choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=20, null=True)),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_dayOfWeek', to='potato.fhir_gp_timing')),
            ],
        ),
    ]
