# Generated by Django 5.1.5 on 2025-01-19 01:29

import potato.FHIR_DataTypes.FHIR_primitive
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0017_auto_20250116_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhir_gp_coding',
            name='code',
            field=potato.FHIR_DataTypes.FHIR_primitive.FHIR_primitive_CodeField(blank=True, max_length=1024, null=True),
        ),
    ]
