# Generated by Django 5.1.5 on 2025-01-25 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0018_alter_fhir_gp_coding_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhir_allergyintolerance',
            name='clinical_status_cc',
        ),
        migrations.AddField(
            model_name='fhir_allergyintolerance',
            name='clinical_status_cc',
            field=models.ForeignKey(blank=True, limit_choices_to={'binding__binding_rule': 'https://www.hl7.org/fhir/valueset-allergyintolerance-clinical.html'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergyintolerance_clinicalstatus', to='potato.fhir_gp_coding'),
        ),
    ]
