# Generated by Django 5.1.5 on 2025-02-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0019_remove_fhir_allergyintolerance_clinical_status_cc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhir_allergyintolerance',
            name='clinical_status_cc',
        ),
        migrations.RemoveField(
            model_name='fhir_allergyintolerance',
            name='criticality_code',
        ),
        migrations.AddField(
            model_name='fhir_allergyintolerance',
            name='clinical_status_cc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'binding__binding_rule': 'https://www.hl7.org/fhir/valueset-allergyintolerance-clinical.html'}, null=True, related_name='allergyintolerance_clinicalstatus', to='potato.fhir_gp_coding'),
        ),
        migrations.AddField(
            model_name='fhir_allergyintolerance',
            name='criticality_code',
            field=models.ManyToManyField(blank=True, limit_choices_to={'binding__binding_rule': 'https://www.hl7.org/fhir/valueset-allergy-intolerance-criticality.html'}, null=True, to='potato.fhir_gp_coding'),
        ),
    ]
