# Generated by Django 5.1.5 on 2025-02-08 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0021_alter_fhir_allergyintolerance_clinical_status_cc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fhir_allergyintolerance',
            name='criticality_code',
        ),
        migrations.AddField(
            model_name='fhir_allergyintolerance',
            name='criticality_code',
            field=models.ForeignKey(blank=True, limit_choices_to={'binding__binding_rule': 'https://www.hl7.org/fhir/valueset-allergy-intolerance-criticality.html'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergyintolerance_criticality', to='potato.fhir_gp_coding'),
        ),
    ]
