from django.db import models
from .models_dir.FHIR_DataTypes.FHIR_primitive import *
from .models_dir.FHIR_DataTypes.FHIR_generalpurpose import *
from .models_dir.FHIR_DataTypes.FHIR_metadata import *
#keeping resources in separate files repeats some import boilerplate
#but maybe easier to manage when there are a lot of resources (nicer git history?)
from .models_dir.FHIR_Resources.AllergyIntolerance import *
from .models_dir.FHIR_Resources.Account import *
from .models_dir.FHIR_Resources.Availability import *
from .models_dir.FHIR_Resources.Appointment import *
from .models_dir.FHIR_Resources.Binary import *
from .models_dir.FHIR_Resources.BiologicallyDerivedProduct import *
from .models_dir.FHIR_Resources.CarePlan import *
from .models_dir.FHIR_Resources.CareTeam import *
from .models_dir.FHIR_Resources.ClaimResponse import *
from .models_dir.FHIR_Resources.Communication import *
from .models_dir.FHIR_Resources.Condition import *
from .models_dir.FHIR_Resources.Coverage import *
from .models_dir.FHIR_Resources.Device import *
from .models_dir.FHIR_Resources.DeviceDefinition import *
from .models_dir.FHIR_Resources.DeviceRequest import *
from .models_dir.FHIR_Resources.DocumentReference import *
from .models_dir.FHIR_Resources.DiagnosticReport import *
from .models_dir.FHIR_Resources.Encounter import *
from .models_dir.FHIR_Resources.Endpoint import *
from .models_dir.FHIR_Resources.Event import *
from .models_dir.FHIR_Resources.GenomicStudy import *
from .models_dir.FHIR_Resources.Group import *
from .models_dir.FHIR_Resources.HealthcareService import *
from .models_dir.FHIR_Resources.ImagingStudy import *
from .models_dir.FHIR_Resources.Immunization import *
from .models_dir.FHIR_Resources.ImmunizationRecommendation import *
from .models_dir.FHIR_Resources.Location import *
from .models_dir.FHIR_Resources.Medication import *
from .models_dir.FHIR_Resources.MedicationAdministration import *
from .models_dir.FHIR_Resources.MedicationDispense import *
from .models_dir.FHIR_Resources.MedicationRequest import *
from .models_dir.FHIR_Resources.MedicationStatement import *
from .models_dir.FHIR_Resources.NutritionOrder import *
from .models_dir.FHIR_Resources.NutritionProduct import *
from .models_dir.FHIR_Resources.Observation import *
from .models_dir.FHIR_Resources.ObservationDefinition import *
from .models_dir.FHIR_Resources.Organization import *
from .models_dir.FHIR_Resources.Patient import *
from .models_dir.FHIR_Resources.Practitioner import *
from .models_dir.FHIR_Resources.PractitionerRole import *
from .models_dir.FHIR_Resources.Procedure import *
from .models_dir.FHIR_Resources.Provenance import *
from .models_dir.FHIR_Resources.RelatedPerson import *
from .models_dir.FHIR_Resources.RequestOrchestration import *
from .models_dir.FHIR_Resources.ServiceRequest import *
from .models_dir.FHIR_Resources.Slot import *
from .models_dir.FHIR_Resources.Substance import *
from .models_dir.FHIR_Resources.VirtualServiceDetail import *
from .models_dir.FHIR_Resources.VisionPrescription import *
