binding = "https://www.hl7.org/fhir/valueset-participation-role-type.html"
codings = [
{
"system" : "http://terminology.hl7.org/CodeSystem/provenance-participant-type",
"version" : "???",
"coding" : [{'code': 'enterer', 'display': 'Enterer', 'definition': 'A person entering the data into the originating system'}, {'code': 'performer', 'display': 'Performer', 'definition': 'A person, animal, organization or device that who actually and principally carries out the activity'}, {'code': 'author', 'display': 'Author', 'definition': 'A party that originates the resource and therefore has responsibility for the information given in the resource and ownership of this resource'}, {'code': 'verifier', 'display': 'Verifier', 'definition': 'A person who verifies the correctness and appropriateness of activity'}, {'code': 'legal', 'display': 'Legal Authenticator', 'definition': 'The person authenticated the content and accepted legal responsibility for its content'}, {'code': 'attester', 'display': 'Attester', 'definition': 'A verifier who attests to the accuracy of the resource'}, {'code': 'informant', 'display': 'Informant', 'definition': 'A person who reported information that contributed to the resource'}, {'code': 'custodian', 'display': 'Custodian', 'definition': 'The entity that is accountable for maintaining a true an accurate copy of the original record'}, {'code': 'assembler', 'display': 'Assembler', 'definition': "A device that operates independently of an author on custodian's algorithms for data extraction of existing information for purpose of generating a new artifact."}, {'code': 'composer', 'display': 'Composer', 'definition': 'A device used by an author to record new information, which may also be used by the author to select existing information for aggregation with newly recorded information for the purpose of generating a new artifact.'}]
},
{
"system" : "http://dicom.nema.org/resources/ontology/DCM",
"version" : "???",
"coding" : [{'code': '110150', 'display': 'Application', 'definition': 'Audit participant role ID of software application.'}, {'code': '110151', 'display': 'Application Launcher', 'definition': 'Audit participant role ID of software application launcher, i.e., the entity that started or stopped an application.'}, {'code': '110152', 'display': 'Destination Role ID', 'definition': 'Audit participant role ID of the receiver of data.'}, {'code': '110153', 'display': 'Source Role ID', 'definition': 'Audit participant role ID of the sender of data.'}, {'code': '110154', 'display': 'Destination Media', 'definition': 'Audit participant role ID of media receiving data during an export.'}, {'code': '110155', 'display': 'Source Media', 'definition': 'Audit participant role ID of media providing data during an import.'}]
},
{
"system" : "http://terminology.hl7.org/CodeSystem/extra-security-role-type",
"version" : "???",
"coding" : [{'code': 'authserver', 'display': 'Authorization Server', 'definition': "An entity providing authorization services to enable the electronic sharing of health-related information based on resource owner's preapproved permissions. For example, an UMA Authorization Server[UMA]"}, {'code': 'datacollector', 'display': 'Data Collector', 'definition': "An entity that collects information over which the data subject may have certain rights under policy or law to control that information's management and distribution by data collectors, including the right to access, retrieve, distribute, or delete that information."}, {'code': 'dataprocessor', 'display': 'Data Processor', 'definition': "An entity that processes collected information over which the data subject may have certain rights under policy or law to control that information's management and distribution by data processors, including the right to access, retrieve, distribute, or delete that information."}, {'code': 'datasubject', 'display': 'Data Subject', 'definition': "A person whose personal information is collected or processed, and who may have certain rights under policy or law to control that information's management and distribution by data collectors or processors, including the right to access, retrieve, distribute, or delete that information."}, {'code': 'humanuser', 'display': 'Human User', 'definition': 'The human user that has participated.'}]
},
]
