binding = "https://www.hl7.org/fhir/valueset-languages.html"
codings = [
    {
        "system": "http://terminology.hl7.org/5.1.0/CodeSystem-v3-ietf3066.html",
        "version": "2.0.1",
        "coding": [
            {'code': 'ar', 'display': 'Arabic'},
            {'code': 'bg', 'display': 'Bulgarian'},
            {'code': 'bg-BG', 'display': 'Bulgarian (Bulgaria)'},
            {'code': 'bn', 'display': 'Bengali'},
            {'code': 'cs', 'display': 'Czech'},
            {'code': 'cs-CZ', 'display': 'Czech (Czechia)'},
            {'code': 'bs', 'display': 'Bosnian'},
            {'code': 'bs-BA', 'display': 'Bosnian (Bosnia and Herzegovina)'},
            {'code': 'da', 'display': 'Danish'},
            {'code': 'da-DK', 'display': 'Danish (Denmark)'},
            {'code': 'de', 'display': 'German'},
            {'code': 'de-AT', 'display': 'German (Austria)'},
            {'code': 'de-CH', 'display': 'German (Switzerland)'},
            {'code': 'de-DE', 'display': 'German (Germany)'},
            {'code': 'el', 'display': 'Greek'},
            {'code': 'el-GR', 'display': 'Greek (Greece)'},
            {'code': 'en', 'display': 'English'},
            {'code': 'en-AU', 'display': 'English (Australia)'},
            {'code': 'en-CA', 'display': 'English (Canada)'},
            {'code': 'en-GB', 'display': 'English (Great Britain)'},
            {'code': 'en-IN', 'display': 'English (India)'},
            {'code': 'en-NZ', 'display': 'English (New Zealand)'},
            {'code': 'en-SG', 'display': 'English (Singapore)'},
            {'code': 'en-US', 'display': 'English (United States)'},
            {'code': 'es', 'display': 'Spanish'},
            {'code': 'es-AR', 'display': 'Spanish (Argentina)'},
            {'code': 'es-ES', 'display': 'Spanish (Spain)'},
            {'code': 'es-UY', 'display': 'Spanish (Uruguay)'},
            {'code': 'et', 'display': 'Estonian'},
            {'code': 'et-EE', 'display': 'Estonian (Estonia)'},
            {'code': 'fi', 'display': 'Finnish'},
            {'code': 'fr', 'display': 'French'},
            {'code': 'fr-BE', 'display': 'French (Belgium)'},
            {'code': 'fr-CH', 'display': 'French (Switzerland)'},
            {'code': 'fr-FR', 'display': 'French (France)'},
            {'code': 'fi-FI', 'display': 'Finnish (Finland)'},
            {'code': 'fr-CA', 'display': 'French (Canada)'},
            {'code': 'fy', 'display': 'Frisian'},
            {'code': 'fy-NL', 'display': 'Frisian (Netherlands)'},
            {'code': 'hi', 'display': 'Hindi'},
            {'code': 'hr', 'display': 'Croatian'},
            {'code': 'hr-HR', 'display': 'Croatian (Croatia)'},
            {'code': 'is', 'display': 'Icelandic'},
            {'code': 'is-IS', 'display': 'Icelandic (Iceland)'},
            {'code': 'it', 'display': 'Italian'},
            {'code': 'it-CH', 'display': 'Italian (Switzerland)'},
            {'code': 'it-IT', 'display': 'Italian (Italy)'},
            {'code': 'ja', 'display': 'Japanese'},
            {'code': 'ko', 'display': 'Korean'},
            {'code': 'lt', 'display': 'Lithuanian'},
            {'code': 'lt-LT', 'display': 'Lithuanian (Lithuania)'},
            {'code': 'lv', 'display': 'Latvian'},
            {'code': 'lv-LV', 'display': 'Latvian (Latvia)'},
            {'code': 'nl', 'display': 'Dutch'},
            {'code': 'nl-BE', 'display': 'Dutch (Belgium)'},
            {'code': 'nl-NL', 'display': 'Dutch (Netherlands)'},
            {'code': 'no', 'display': 'Norwegian'},
            {'code': 'no-NO', 'display': 'Norwegian (Norway)'},
            {'code': 'pa', 'display': 'Punjabi'},
            {'code': 'pl', 'display': 'Polish'},
            {'code': 'pl-PL', 'display': 'Polish (Poland)'},
            {'code': 'pt', 'display': 'Portuguese'},
            {'code': 'pt-PT', 'display': 'Portuguese (Portugal)'},
            {'code': 'pt-BR', 'display': 'Portuguese (Brazil)'},
            {'code': 'ro', 'display': 'Romanian'},
            {'code': 'ro-RO', 'display': 'Romanian (Romania)'},
            {'code': 'ru', 'display': 'Russian'},
            {'code': 'ru-RU', 'display': 'Russian (Russia)'},
            {'code': 'sk', 'display': 'Slovakian'},
            {'code': 'sk-SK', 'display': 'Slovakian (Slovakia)'},
            {'code': 'sl', 'display': 'Slovenian'},
            {'code': 'sl-SI', 'display': 'Slovenian (Slovenia)'},
            {'code': 'sr', 'display': 'Serbian'},
            {'code': 'sr-RS', 'display': 'Serbian (Serbia)'},
            {'code': 'sv', 'display': 'Swedish'},
            {'code': 'sv-SE', 'display': 'Swedish (Sweden)'},
            {'code': 'te', 'display': 'Telugu'},
            {'code': 'zh', 'display': 'Chinese'},
            {'code': 'zh-CN', 'display': 'Chinese (China)'},
            {'code': 'zh-HK', 'display': 'Chinese (Hong Kong)'},
            {'code': 'zh-SG', 'display': 'Chinese (Singapore)'},
            {'code': 'zh-TW', 'display': 'Chinese (Taiwan)'},
        ]
    },
]